### ISSUE TITLE
regression: Using with htm throws error

### ISSUE THREAD

**Issue by kristoferjoseph** [preactjs/preact-render-to-string#125]
While trying to use the latest version of `preact-render-to-string` with `htm` there is an error thrown.
"unable to find preact"
Installing preact does not fix this issue.

**Comment by kristoferjoseph** [comment]
OK Found the cause.
I was using `import { html, render } from 'https://unpkg.com/htm/preact/standalone.module.js'`
and `preact-render-to-string` needs `preact` to be installed in `node_modules`

**Comment by marvinhagemeister** [comment]
It should work out of the box in the browser. Can you share a codesandbox or an error message?
