### ISSUE TITLE
Calling setState from componentWillMount fails with `Cannot set property 'updated' of undefined`

### ISSUE THREAD

**Issue by xtroncode** [preactjs/preact-render-to-string#126]
I am trying to switch to preact but stumbled upon the following issue in a dependency  https://github.com/oliviertassinari/react-swipeable-views/blob/master/packages/react-swipeable-views-utils/src/virtualize.js , it calls `setState` from within `componentWillMount` and ends up breaking server render. 

I have tried to reproduce the issue in the following sandbox: https://codesandbox.io/s/withered-cdn-12mby 

Please let know if more info is needed or if I can help in someway to fix this.

**Comment by marvinhagemeister** [comment]
@xtroncode Awesome, thank you so much for the report and the codesandbox link :tada: With it I could easily reproduce it and quickly find a fix :100: The fix is included in version `5.1.2` and that should be available on npm in the next few minutes :+1:

**Comment by xtroncode** [comment]
@marvinhagemeister thank you so much for the quick fix :100:
