### ISSUE TITLE
regression: Changes in getDerivedStateFromProps are lost

### ISSUE THREAD

**Issue by krasnoperov** [preactjs/preact-render-to-string#137]
It seems that [flush of pending state updates](https://github.com/preactjs/preact-render-to-string/commit/5e7acf3115edcddbd4bb79a46d336e109824a3a3#diff-1fdf421c05c1140f6d71444ea2b27638R118) for `componentWillMount` must not happen in case of `getDerivedStateFromProps`

Examples:

preact-render-to-string@5.1.1: good: correct name
https://codepen.io/krasnoperov/pen/oNXxZxP

preact-render-to-string@5.1.4: fail: unknown name
https://codepen.io/krasnoperov/pen/LYVNWRJ

**Comment by marvinhagemeister** [comment]
@krasnoperov Good catch, can you make PR?

**Comment by sullenor** [comment]
Looks like I faced a similar issue using 'react-transition-group'. Results of [getDerivedStateFromProps](https://github.com/reactjs/react-transition-group/blob/9e3b2d3c09b78e755bdc837b7b38337812ede2c9/src/TransitionGroup.js#L62) are not saved, so `Object.values` throws an exception for `undefined` value during [render](https://github.com/reactjs/react-transition-group/blob/9e3b2d3c09b78e755bdc837b7b38337812ede2c9/src/TransitionGroup.js#L91) call.

Downgrading to preact-render-to-string@5.1.1 helps.
