### ISSUE TITLE
render function  converts `htmlFor` to `for` attribute 

### ISSUE THREAD

**Issue by moahammadalt** [preactjs/preact-render-to-string#151]
suddenly the render function starts to convert `htmlFor` attributes to `for` and that causing me problems in snapshot tests.

for a component like this:

`<Label htmlFor={input.name}>{label}</Label>`

it is converting it to like this in the snapshots:

`<label for="checkbox">label</label>`

here is my jest snapshot configuration in package json:

```
"snapshotSerializers": [
  "jest-serializer-html-string"
],
```

and i am creating my snapshot tests like that:

```
it(`renders markup correctly`, () => {
    const tree = renderer(<SomeComponent />);
    expect(tree).toMatchSnapshot();
});
```

the problem is that htmlFor is converted to for in the snapshot file and that is causing me problems.

it was converted right before but recently, it starts to convert it to for, hope there is any way to keep htmlFor attribute as it is in the snapshots tests.

**Comment by marvinhagemeister** [comment]
> for a component like this:
>
> `<Label htmlFor={input.name}>{label}</Label>`
>
> it is converting it to like this in the snapshots:
>
> `<label for="checkbox">label</label>`

@moahammadalt I'm a bit confused by the different casings of the tag name. Is the issue that you're describing that we also change components to DOM elements `Label` -> `label`?

**Comment by moahammadalt** [comment]
@marvinhagemeister changing the Label to label is totally fine because I know it renders only HTML not component, the issue here is only with changing the attribute name from htmlFor to for.

**Comment by sventschui** [comment]
I am not 100% sure if I understand your case correctly so you might want to add a more detailed example if my answer doesn‘t help. 

It is expected to turn `htmlFor` to `for` when rendering a `label`, since htmlFor is the JS DOM API and for is the HTML attribute:
`<label htmlFor="foo" ...` -> `<label for="foo" ...`

It is NOT expected to turn `htmlFor` to `for` when rendering a component:
`<ArbitraryComponent htmlFor="foo" ...` -> `<ArbitraryComponent for="foo" ...`

**Comment by moahammadalt** [comment]
@sventschui what you have said make sense actually, but I am just wondering how it was rendering the same htmlFor attribute a few days ago!

anyway, I manage solving this by converting all `htmlFor` attributes to` for` in my components, closing the issue.
