### ISSUE TITLE
not a valid HTML tag name error

### ISSUE THREAD

**Issue by rossPatton** [preactjs/preact-render-to-string#159]
The error:

`undefined: [object Object] is not a valid HTML tag name in <[object Object] value="[object Object]">`

code:
```
...imports

const jsx = (
    <Provider store={store as any}>
      <StaticRouter
        context={{}}
        location={ctx.request.url}>
        <AppShell />
      </StaticRouter>
    </Provider>
  );

  console.log('jsx ? ', render(jsx));
```

when I run it in jsx mode, i get a slightly more useful error but still not able to pin down just what the invalid tag is:
```

Error: [object Object] is not a valid HTML tag name in <[object Object]
  value={
    Object {
      "history": Object {
        "action": "POP",
        "block": [Function anonymous],
        "createHref": [Function createHref],
        "go": [Function anonymous],
        "goBack": [Function anonymous],
        "goForward": [Function anonymous],
        "listen": [Function anonymous],
        "location": Object {
          "hash": "",
          "pathname": "/",
          "search": "",
          "state": undefined
        },
        "push": [Function anonymous],
        "replace": [Function anonymous]
      },
      "location": Object {
        "hash": "",
        "pathname": "/",
        "search": "",
        "state": undefined
      },
      "match": Object {
        "isExact": true,
        "params": Object {},
        "path": "/",
        "url": "/"
      },
      "staticContext": Object {}
    }
  }
>
```

I'm trying to switch my app over from react to preact, and this is the only thing that's blocking me. When I run the app without SSR, just using preact to mount on the client only, everything works fine. No errors.

Given that html is so... loose, wouldn't a warning be better here?

**Comment by marvinhagemeister** [comment]
No, this is an error and Preact cannot guarantee a correct output at this point. It needs to throw an error. Essentially what is happening is that something tries to render an `object` as a component, which is not valid.

```jsx
const Foo = { value: myHistory };

// Invalid, "Foo" is not a component
render(<Foo />); 

// without JSX it looks like this
render(h({ value: myHistory }, null));
```

Only `strings` for native HTML nodes or `functions/classes` for Components are valid as the first parameter to `h/createElement`, not an `object`.

It's hard to know without seeing the code of the components in the provided snippets what's going on. Looking at their source will likely provide answers. If you provide a [codesandbox](https://codesandbox.io) where the error can be reproduced we can take a look ourselves :+1:

**Comment by rossPatton** [comment]
Well, yeah, I understand the error, but that's not where my confusion lies

What I don't understand is why `react`, `preact` and `preact-compat` are all capable of rendering this setup, but `preact-render-to-string` returns a invalid tag name error. To be clear - if I convert things to client side rendering only, with `preact`, I have no issue

That seems like a bug to me. I would assume `preact-render-to-string` uses the same renderer as `preact` right? 

Now of course, it's not `StaticRouter` on the client, it's `BrowserRouter`, but they are functionally pretty similar and `react-router` is a super common dependency, so it would be odd for `StaticRouter` to be the problem, imo. And if that is the case, it's kind of a deal-breaker, or at the very least, it's just really not worth the hassle to switch it out, imo

**Comment by marvinhagemeister** [comment]
Happy to take a look at it. Can you provide a codesandbox or repo where the issue can be reproduced? Hard for us to guess what could be wrong rather than inspecting the error itself.

**Comment by regan-karlewicz** [comment]
Hi @rossPatton. I have some insight here that might help you after dealing with this issue.

We were getting this error because we weren't including our `node_modules` into our webpack config, and they weren't getting aliased. 

In our webpack config we had something like:

```
aliases: [
     react: 'preact/compat',
    'react-dom': 'preact/compat',
]
```

But our webpack config was using `webpack-node-externals` to skip the `node_modules` folder. 

This was causing the `node_modules` to still have imports from React, which are not compatible with preact. In our case, it was using `React.createContext`, which `preact-render-to-string` doesn't know how to serialize. 

Make sure when you are bundling it, that you are also running `react-router` through your aliases. My bet is you are not aliasing in `preact/compat` in your node_modules.

Additionally, check out [preact-router](https://github.com/preactjs/preact-router). The README says that it is not a complete replacement for `react-router`, but you can still use `react-router` "as long as you alias in preact/compat".

**Comment by rossPatton** [comment]
I am definitely aliasing, but you are correct that since I'm on the server i was excluding `node_modules` so maybe that was it

This is probably not the 'correct' solution, but in the end I realized everything worked fine with rendering via react on server (even with streaming, which is a feature I don't think preact supports?), and preact on client. It's a little irksome to have both react and preact installed, but so far it seems to work fine.

**Comment by marvinhagemeister** [comment]
FYI The streaming feature in React's server renderer is not what it sounds like until their concurrent idea is production ready. They render to string synchronously like is and put the result in a node steam. So the rendering part remains synchronous.

**Comment by rossPatton** [comment]
Huh, good to know!
