### ISSUE TITLE
srcSet not converted to srcset

### ISSUE THREAD

**Issue by SimenB** [preactjs/preact-render-to-string#18]
This works correctly in preact proper

**Comment by developit** [comment]
Good catch! Open to a PR, or I can do it whenever I get a chance. I'd like to add an `ATTR_MAP` mapping like:

```js
const ATTR_MAP = {
  'srcSet': 'srcset'
};
```

Perhaps the keys on the left could be lowercase and we'd compare the lowercase'd JSX attribute names.

**Comment by SimenB** [comment]
Can't we do `toLowerCase` on everything that's passed onto DOM nodes?

**Comment by developit** [comment]
nah, SVG attributes are case-sensitive (`viewBox`).
