### ISSUE TITLE
Potential performance issues between v5.1.2-v5.1.12

### ISSUE THREAD

**Issue by JimLiu** [preactjs/preact-render-to-string#180]
Our application recently upgraded `preact-render-to-string` from `v5.1.2` to `v5.1.12`, that caused a big performance issue.
![image](https://user-images.githubusercontent.com/648674/110156104-2c89b000-7dac-11eb-81b7-440c6b3c0d7e.png)

It's getting back to normal after we rolled back `preact-render-to-string` to `v5.1.2`.
![image](https://user-images.githubusercontent.com/648674/110157136-7757f780-7dad-11eb-9835-5a5711e0d2ef.png)

Not sure what is causing the issue.
https://github.com/preactjs/preact-render-to-string/compare/415a377..8be957a

Might be this one: https://github.com/preactjs/preact-render-to-string/pull/170/files
![image](https://user-images.githubusercontent.com/648674/110158035-82f7ee00-7dae-11eb-967e-d9810ae9be78.png)

**Comment by JimLiu** [comment]
After rolled back to 5.1.2, it got better, but CPU is still high, and got a cpu profile from production
It took 100ms to render preact components
![image](https://user-images.githubusercontent.com/648674/110218008-f5370400-7e7c-11eb-83bb-d1ea0db9fd86.png)

**Comment by marvinhagemeister** [comment]
@JimLiu Thank you so much for the bug report! It seems like entity encoding indeed got slower with the string building approach. Using a standard `str.replace´ call speeds it up significantly for me

**Comment by marvinhagemeister** [comment]
Released as `5.1.13` 🎉
