### ISSUE TITLE
Performance issue with 5.1.15

### ISSUE THREAD

**Issue by JimLiu** [preactjs/preact-render-to-string#191]
I reported a performance issue last time #180, the issue had been resolved after we rolled back to `v5.1.2`

this week we deployed the new version `v5.1.15`, got performance issue again.
![image](https://user-images.githubusercontent.com/648674/111706776-dfc4c100-8810-11eb-9473-760e1a59ace9.png)

and got back to normal after rolled back to `v5.1.2`

I checked the code between `v5.1.2` to `v5.1.15` [415a377..9a5e748](https://github.com/preactjs/preact-render-to-string/compare/415a377..9a5e748#diff-9c0ec1b0a889e599f3ff81590864dd9dc65684a86b41f1da75acc53fafed12e3R7), memory leak?!

The code is running on the server side!

![image](https://user-images.githubusercontent.com/648674/111709436-99259580-8815-11eb-9b04-960e6ced7451.png)

**Comment by developit** [comment]
@JimLiu This performance issue was addressed in `5.1.16`, which does not do any memoization. Are you able to try that version?

https://github.com/preactjs/preact-render-to-string/releases/tag/v5.1.16

**Comment by JimLiu** [comment]
> @JimLiu This performance issue was addressed in `5.1.16`, which does not do any memoization. Are you able to try that version?
> 
> https://github.com/preactjs/preact-render-to-string/releases/tag/v5.1.16

Thank you for your reply, will try 5.1.16 tomorrow

**Comment by developit** [comment]
Awesome! We're working on landing some performance improvements - perhaps we could ping you when they're ready to test and get your feedback prior to release?

**Comment by JimLiu** [comment]
Sure, preact render is currently a bottleneck for our performance.

We'd be happy to see a significant performance improvement with it as well. Please let me know when the new version is ready and I'll give you feedback.

**Comment by JimLiu** [comment]
@developit 
We deployed v5.1.16 to production, it's better than v5.1.15 for sure, but you can still see a significant increase in CPU at some period of time. I'll need more time to keep observing.

![image](https://user-images.githubusercontent.com/648674/111828816-da6f8100-88b9-11eb-84ad-1e703a2909fc.png)

**Comment by JimLiu** [comment]
The performance of v5.1.16 is not as good as that of v5.1.2
![image](https://user-images.githubusercontent.com/648674/111841977-ced98580-88cc-11eb-8081-b87bf8f4d893.png)

**Comment by JimLiu** [comment]
I tried to save preact-render-to-string to local, and use the index.js file from v5.1.16 and utils.js from v5.1.2, this is the result:
![image](https://user-images.githubusercontent.com/648674/112082024-a06cdc00-8b52-11eb-8af5-9a431922cb85.png)

**Comment by JimLiu** [comment]
@developit 
I think I find the root cause of our performance issue, most likely it's caused by this change:
https://github.com/preactjs/preact-render-to-string/pull/175/files#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556R185

Our graph is getting back to normal after I disabled that line 
```js
if (options.diffed) options.diffed(vnode);
```
![image](https://user-images.githubusercontent.com/648674/112227510-cd29fd80-8bfd-11eb-9791-add1c012888c.png)

![image](https://user-images.githubusercontent.com/648674/112227791-314cc180-8bfe-11eb-99d3-4eb2b9d494d4.png)


Could we have an option to disable it? or disable it by default, we actually don't need that line

**Comment by developit** [comment]
You can just remove that global hook yourself:

```
import { options } from 'preact';

options.diffed = null;
```

Though I'd like to understand how it's being set - `options.diffed` is used by `preact/debug`, `preact/compat` and `preact/hooks` - which of those are you using?  If you're importing `preact/debug` on the server that would certainly increase the cost of rendering (we don't recommend doing so).

**Comment by JimLiu** [comment]
We don't use `preact/debug` on both production and server side for sure!
We are using `preact/compat` and `preact/hooks` for redux and react-redux and other customize hooks , not sure if we can disable `options.diffed` or not.

it would great to have an option to disable this line of code:
```js
if (options.diffed) options.diffed(vnode);
````
https://github.com/preactjs/preact-render-to-string/blob/2a6f332fe2d7e30ec0e5121bfa62bfb9ca728763/src/index.js#L187

**Comment by JimLiu** [comment]
Well, I can now summarize what this performance issue is all about.

First, in this PR #175, a new line of code has been added.

https://github.com/preactjs/preact-render-to-string/blob/2a6f332fe2d7e30ec0e5121bfa62bfb9ca728763/src/index.js#L187

This code looks simple, but when the preact app uses hooks, then the `options.diffed` function is called, and there is a line of code in preact's `options.diffed` that causes a memory leak.

This line of code will add the current component to a global array of `afterPaintEffects`, which will not be cleaned up after the request ends, and as more and more requests are made, this array will get bigger and bigger and will eventually overflow.

https://github.com/preactjs/preact/blob/e523a82cda1d982b6fa82d23cc7539f5f5b4701d/hooks/src/index.js#L55
```js
options.diffed = vnode => {
	if (oldAfterDiff) oldAfterDiff(vnode);

	const c = vnode._component;
	if (c && c.__hooks && c.__hooks._pendingEffects.length) {
		afterPaint(afterPaintEffects.push(c)); // the component is added to the global array `afterPaintEffects`
	}
	currentComponent = previousComponent;
};
```

I'm sorry I'm not familiar with the preact source code and can't contribute pr, hopefully this will be fixed soon

![image](https://user-images.githubusercontent.com/648674/112254023-d632c300-8c2d-11eb-9162-90a189aac9e0.png)

**Comment by developit** [comment]
@JimLiu 5.1.17 is released and includes a fix for the options.diffed leak. Can you try upgrading to they version (without unsetting/removing the options.diffed() call)? It should have significantly better performance than 5.1.2!

**Comment by JimLiu** [comment]
@developit 
Memory leak again

![image](https://user-images.githubusercontent.com/648674/112913126-b2a0ca00-90be-11eb-9c63-ef6ba1bb3503.png)
![image](https://user-images.githubusercontent.com/648674/112913201-d532e300-90be-11eb-9f56-6fc477c0213e.png)

**Comment by developit** [comment]
@JimLiu I believe there was an oversight in the fix landed in 5.1.17. I am publishing 5.1.18 with an amended fix.

**Comment by JimLiu** [comment]
I'll test it tomorrow, btw, my preact version is `"preact": "^10.0.4",`

**Comment by developit** [comment]
oh! my goodness, that's quite old. Is there something preventing you from upgrading to a more recent version of Preact?
