### ISSUE TITLE
Question: RenderToString with context and Provider

### ISSUE THREAD

**Issue by remko79** [preactjs/preact-render-to-string#198]
I'm trying to find a nice way to let my components set some response headers (for example cache params, response status, etc) using the 'context' parameter of the renderToString function.

A simplified example for the response code is:
```js
import express from 'express';
import renderToString from 'preact-render-to-string';

const App = ({ url }, context) => {
  console.log('context', context);
  // outputs: { some: 'thing' }

  context.some = 'thing else';
  context.customStatus = 404;
  return (<div>{`Hello world on url: ${url}`}</div>);
};

const server = express();

server.get('/*', async (req, res) => {
  const myApp = (<App url={req.url} />);

  const context = { some: 'thing' };
  const content = renderToString(myApp, context);
  console.log('context', context);
  // outputs: { some: 'thing else', customStatus: 404 }

  if (context.customStatus) {
    res.status(context.customStatus);
  }
  res.send(content);
});

server.listen(3000, () => {
  console.log('Listening on http://localhost:3000');
});
```
Now this example works fine where I can set the status code directly in the component and send the 404 to the client.

However if I wrap the <App> in a Provider, I can't use the context directly anymore in the component, see the following example:

```js
import express from 'express';
import renderToString from 'preact-render-to-string';
import { createClient, fetchExchange, Provider, ssrExchange } from '@urql/preact';

const gqlClient = createClient({
  url: '<some url>',
  exchanges: [
    ssrExchange({ isClient: false }),
    fetchExchange,
  ],
});

const App = ({ url }, context) => {
  console.log('context', context);
  // outputs: { some: 'thing', __cC0: { ... } }

  // this doesn't work anymore:
  context.some = 'thing else';
  context.customStatus = 404;

  return (<div>{`Hello world on url: ${url}`}</div>);
};

const server = express();

server.get('/*', async (req, res) => {
  const myApp = (
    <Provider value={gqlClient}>
      <App url={req.url} />
    </Provider>
  );

  const context = { some: 'thing' };
  const content = renderToString(myApp, context);
  console.log('context', context);
  // outputs: { some: 'thing' }

  if (context.customStatus) {
    res.status(context.customStatus);
  }
  res.send(content);
});

server.listen(3000, () => {
  console.log('Listening on http://localhost:3000');
});
```

Now I could do this in the component to update the context which of course isn't the way as __cC0 is hardcoded:

```js
  context.__cC0.context.some = 'thing else';
  context.__cC0.context.customStatus = 404;
```

I have 2 questions:
1. Is using the context the 'way to go'? It's not just about the error code, but also (in the future) different cache response headers based on which page will be rendered.
2. If I can find the __cC0 name, maybe I can pass it together with the original context. Is this the way to get it: `const myAppIdentifier = myApp.type.__.__c`?

**Comment by marvinhagemeister** [comment]
The context argument of function components is not mutable and there are no guarantees that it is the same one as the one from the parent components. The conceptual model in Preact is that you trigger an update higher up in the tree instead of modifying an object directly. When a component receives an update it will update all it's children (unless someone bails out) and thereby ensuring that the whole tree stays in sync with the data layer.

The newer `createContext`-API is what you're looking for.

```js
import { createContext } from "preact";
import { useContext, useState } from "preact/hooks";

const MyContext = createContext();

function App() {
  const [value, setValue] = useState(0);
  return <MyContext.Provider value={{ value, setValue }}>
    <MyComponent />
  </MyContext.Provider>
}

function MyComponent() {
  // Read context value
  const { value, setValue } = useContext(MyContext);

  return <div>
    <p>Value: {value}</p>
    <button onClick={() => setValue(value +1)}>increment</button>
  </div> 
}
```

The context API is the right one for your use case as it sounds like a piece of shared state that should be shared across components. I would recommend against hacking into Preact's internals of the Context API.

**Comment by remko79** [comment]
Thanks for your reply. I understand what you are saying, but how then would you get that value back in the express section to set the response status/headers? 

In your example you are updating the value in the App component, but I need that value higher up to do `res.set` or `res.status`.

**Comment by marvinhagemeister** [comment]
I'd pass an object to the `App` component where the changes will be reflected into. After rendering this object holds all information for further processing.

```js
function App(props) {
  const [status, setStatus] = useState(200);

  // Set headers
  props.headers.status = status;
  
  return <MyContext.Provider value={{ status, setStatus }}>
    <MyComponent />
  </MyContext.Provider>
}

// This call is synchronous, therefore `headers.status` will
// be set after rendering.
const headers = {};
renderToString(<App headers={headers} />);

console.log(headers.status);
// Logs: 200
```

**Comment by remko79** [comment]
Thanks for the example. I'll start working from this.
