### ISSUE TITLE
Empty class attribute duplicated with preact/compat and SSR

### ISSUE THREAD

**Issue by siancatalyst** [preactjs/preact-render-to-string#208]
**Describe the bug**
When an element is created in preact/compat with className="", rendering it to a string causes two class attributes to be output.

This can happen when using conditional classes returned from the npm `classnames` function, for example.

**To Reproduce**
```
const { createElement } = require("preact/compat");
const render = require("preact-render-to-string");
console.log(render(createElement("a", { className: "" })));
```
Tested with preact v10.6.4 and preact-render-to-string v5.1.19

**Observed behavior**
`<a class class></a>`

**Expected behavior**
`<a class></a>` or `<a class=""></a>`

**Comment by rschristian** [comment]
Thanks for the issue, found the offending bit of code:

https://github.com/preactjs/preact-render-to-string/blob/6214991630fadc4bd52ef59100b3aa715794cd44/src/index.js#L249-L251

Will get a PR together here
