### ISSUE TITLE
Implement `renderToReadableStream` api to allow preact to stream HTML responses from on the server. 

### ISSUE THREAD

**Issue by nicksrandall** [preactjs/preact-render-to-string#210]
I'll totally understand if this is not a priority right now but I thought it couldn't hurt to have an issue to track the request. 

Here is a reference to React's implementation of `renderToReadableStream`: https://github.com/facebook/react/blob/cdb8a1d19d0c0d43a72c3f0fe739b04da247c360/packages/react-dom/src/server/ReactDOMFizzServerBrowser.js#L40

**Comment by jsejcksn** [comment]
@nicksrandall I think the title has a typo: `readerToReadableStream` should be `renderToReadableStream`. Will you update it to improve discoverability?

**Comment by JoviDeCroock** [comment]
We have added [renderToPipeableStream](https://github.com/preactjs/preact-render-to-string/blob/main/src/stream-node.js#L17) and [renderToReadableStream](https://github.com/preactjs/preact-render-to-string/blob/main/src/stream.js#L11) in 6.5.0, this will be available under the [new exports](https://github.com/preactjs/preact-render-to-string/blob/main/package.json#L26-L37)
