### ISSUE TITLE
renderToString breaks hooks

### ISSUE THREAD

**Issue by Samuava** [preactjs/preact-render-to-string#217]
Hook breaks if you call renderToString before initializing the hook in a functional component
```js
import { h } from 'preact'
import { useEffect } from 'preact/hooks'
import renderToString from 'preact-render-to-string'

const FunctionalComponent = () => {
  renderToString(<a>link</a>)
  useEffect(() => console.log('You should see this if the hook does not break'), [])
  return 'Hello world'
}
```

**Comment by Samuava** [comment]
Current workaround: Call renderToString after initializing hooks.

**Comment by Samuava** [comment]
> Effect-Hooks won't run during renderToString, this because of the async nature of hooks. We don't want to start open subscriptions/... we want to create a stringified view of the vdom to be hydrated on the client.
> 
> An rts pass is synchronous while side-effects are asynchronous in nature

**Comment by Samuava** [comment]
@JoviDeCroock I suppose that makes sense, but since renderToString is synchronous and doesn't necessarily have side effects, I would expect it to just work. I don't expect rts to call hooks, but I don't expect it to break hooks in the component that is used in either. Obviously this is not a common use case, but it's not obvious why it's not working.

**Comment by JoviDeCroock** [comment]
I mean, you are using the term "breaks" but aren't really telling us how it breaks. If your definition of breaking is it not getting called that is intended because of the aforementioned reasons, if it crashes that is a whole other story

**Comment by JoviDeCroock** [comment]
Unless you are on an older version that functionality should be restored after RTS completes as shown here https://github.com/preactjs/preact-render-to-string/blob/master/src/index.js#L65 `__s` is the options variable that makes skipping effects apply

**Comment by Samuava** [comment]
@JoviDeCroock Fair enough, we are lagging a little behind on version 10.5.15.

**Comment by nmocruz** [comment]
getting this 'Cannot read properties of null (reading '__H')' too
