### ISSUE TITLE
is it possible to have state functions?

### ISSUE THREAD

**Issue by jonniedarko** [preactjs/preact-render-to-string#221]
I have created an express view engine that uses `renderToString` method

and works fine except when I try to render this:
```
import { h } from 'preact'
import { useState } from 'preact/hooks'

export default function Counter() {
  const [count, setCount] = useState(0)
  const increment = () => setCount(count + 1)
  // You can also pass a callback to the setter
  const decrement = () => setCount((currentCount) => currentCount - 1)

  return (
    <div>
      <p>Count: {count}</p>
      <button onClick={increment}>Increment</button>
      <button onClick={decrement}>Decrement</button>
    </div>
  )
}

```

then `onClick` is stripped and no js functions. 
I end up with this `<div><p>Count: 0</p><button>Increment</button><button>Decrement</button></div>`
Maybe I'm expecting too much but would love to figure out how to get this to work

**Comment by rschristian** [comment]
This is the correct behavior. The point behind a `renderToString` is to create static HTML from your components.

For client side JS, you want to use Preact's [`hydrate()`](https://preactjs.com/guide/v10/api-reference#hydrate) to attach listeners and setup your components.
