### ISSUE TITLE
Object children are rendered as `<undefined>`

### ISSUE THREAD

**Issue by lucacasonato** [preactjs/preact-render-to-string#245]
```js
import render from "https://esm.sh/preact-render-to-string@5.2.4?deps=preact@10.11.0";
import { h } from "https://esm.sh/preact@10.11.0";
console.log(render(h("div", null, { hello: "world" })));
```

```shell
$ deno run test.ts
<div><undefined></undefined></div>
```

**Comment by lucacasonato** [comment]
I think it would make most sense to always throw (because this is always user error), but I understand why that may not make sense as a default for `preact` due to possible size implications.

**Comment by developit** [comment]
My preference here is to silently ignore the object. We have throwing/warning in debug.

**Comment by pitust** [comment]
Fragments are rendered as `<undefined>stuff inside the fragment</undefined>`, which is undesirable as well.

**Comment by marvinhagemeister** [comment]
@pitust please file a new issue for that with details on how to reproduce it. Quickly checked on my end and rendering `Fragments` works as expected.
