### ISSUE TITLE
Call rendering hooks on non-components

### ISSUE THREAD

**Issue by gpoitch** [preactjs/preact-render-to-string#250]
I have some rendering hooks I'm looking to use in preact that will for example modify the `href` of all `<a>` tags. I'd like to reflect the same thing when rendering to string. However, the rendering options hooks are only called for components and not standard tags in preact-render-to-string.

```js
import { options } from 'preact'
  
const originalDiffed = options.diffed
options.diffed = (vnode) => { // Only called for components in preact-render-to-string
  console.log(vnode.type)
  originalDiffed?.(vnode)
}
```

Relatedly, "diffed" sounds like the wrong hook in this context. Maybe render (`__r`) is better but diffed looked like the only public name? FWIW `__r` was only called for components too.

**Comment by JoviDeCroock** [comment]
Looks like it's called for all https://github.com/preactjs/preact-render-to-string/blob/master/src/index.js#L382

**Comment by gpoitch** [comment]
Ah yes working on the latest version, thanks! Forgot I was on a fork 🙈
