### ISSUE TITLE
With Nextjs Error: Objects are not valid as a child. Encountered an object with the keys {} 

### ISSUE THREAD

**Issue by mmdHasan-yazdanPanah** [preactjs/preact-render-to-string#254]
I got this error on the last-release(5.2.5), I am working with Nextjs and entirely using SSG and ISR.
The error only appears on development(which all SSG becomes SSR) and no error on the build.
I am using preact/compat with type-aliasing method.

Solution: downgrade to ver 5.2.2

**Comment by marvinhagemeister** [comment]
Thanks for reaching out. Can you share more information so that we can reproduce the issue on our end? The error will be thrown when an invalid element is passed as a jsx node.

**Comment by mmdHasan-yazdanPanah** [comment]
Yes, exactly the same for me.

**Comment by mcous** [comment]
I'm encountering this issue in a project built with Vite. Haven't nailed down a minimal reproduction yet, but I am using SSG via [vite-plugin-ssr](https://github.com/brillout/vite-plugin-ssr).

`v5.2.3` is the latest "good" version, anything later than that I get `Objects are not valid as a child`. The "objects" in question appear to be numbers and strings in the source code.

**Comment by marvinhagemeister** [comment]
Took a look into this and the reason we throw this error is that we recently added all the missing option hooks in `preact-render-to-string`. This enabled signal subscriptions and `preact/debug` now to work as expected. There is one thing that we didn't account for and that is that right now we don't materialize a text vnode for strings.

```jsx
// input
const vnode = <p>{"foo"}</p>

// preact-render-to-string
const vnode = {
  type: "p"
  _k: [
    "foo"
  ]
}

// preact in browser
const vnode = {
  type: "p",
  _k: [
    { type: null, props: "foo", ... }
  ],
}
```

The check in `preact/debug` doesn't check the `vnode` that gets passed to `options.diffed` directly, but rather what's in the children array.
