### ISSUE TITLE
Rendering shallow makes a Fragment into a <p>

### ISSUE THREAD

**Issue by remko79** [preactjs/preact-render-to-string#262]
Shallow rendering this:
`<><ComponentX /></>`
Creates this:
`<p><ComponentX /></p>`

Is that intended behaviour? Why not just `<ComponentX />`

**Comment by rschristian** [comment]
Could you provide a reproduction by any chance? I'm unable to reproduce this behavior. [Everything seems to be correct from my quick testing](https://esm.rschristian.dev/#Ly8gVHJ5aW5nIHRvIHJlcHJvZHVjZSBwcmVhY3QtcmVuZGVyLXRvLXN0cmluZyMyNjIKLy8gLS0tLS0tLS0tLS0tLS0tLQoKaW1wb3J0IHsgRnJhZ21lbnQsIGgsIHJlbmRlciB9IGZyb20gJ2h0dHBzOi8vY2RuLnNreXBhY2suZGV2L3ByZWFjdCc7CmltcG9ydCB7IHNoYWxsb3dSZW5kZXIgfSBmcm9tICdodHRwczovL2Nkbi5za3lwYWNrLmRldi9wcmVhY3QtcmVuZGVyLXRvLXN0cmluZyc7CmltcG9ydCB7IGh0bWwgfSBmcm9tICdodHRwczovL2Nkbi5za3lwYWNrLmRldi9odG0vcHJlYWN0L3N0YW5kYWxvbmUnOwoKY29uc3QgQ29tcG9uZW50WCA9ICgpID0+IGgoJ2gxJywgbnVsbCwgJ0hlbGxvIFdvcmxkIScpOwpjb25zdCByZXN1bHQgPSBzaGFsbG93UmVuZGVyKGgoRnJhZ21lbnQsIG51bGwsIGgoQ29tcG9uZW50WCkpKTsKCnJlbmRlcihodG1sYDxoMSBzdHlsZT0iY29sb3I6d2hpdGUiPiR7cmVzdWx0fTwvPmAsIGRvY3VtZW50LmJvZHkpOw==).

JSX vs `h` calls (as the above example uses) shouldn't be an issue, you can copy/paste the following into CodePen or something to see the same result:

```jsx
import { h, Fragment, render } from "https://cdn.skypack.dev/preact@10.11.2";
import { shallowRender } from "https://cdn.skypack.dev/preact-render-to-string@5.2.6";

/* @jsx h */
/* @jsxFrag Fragment */

const ComponentX = () => <h1>Hello World</h1>;
const result = shallowRender(<><ComponentX /></>);

render(<h1>{result}</h1>, document.body);
```

Not sure what would cause this though.

**Comment by remko79** [comment]
Thanks for your reply. I've done a bit further investigation into when this exactly happens.

So I have a (simplified) component in file 'index.jsx':
```javascript
export default function Header() {
  return (
    <>
      <div>Test</div>
    </>
  );
}
```
And then if you render this with these commands:
```javascript
import { render, shallowRender } from 'preact-render-to-string';
import Header from './index';

console.log(shallowRender(<Header />));
console.log(render(<Header />));
```
You will notice that the shallow rendering outputs: `<p><div>Test</div></p>` and the normal one: `<div>Test</div>`.

Now of course you could render it using:
```javascript
    console.log(shallowRender(Header()));
    console.log(render(Header()));
```
But that's not really nice ;) I'm trying to use this way to shallow render components for unit tests while keeping the code style (`<Header .... />` with params) similar to my "normal" code

**Comment by remko79** [comment]
After updating to v6 the <p> are now rendered as <d> when using shallow rendering

**Comment by marvinhagemeister** [comment]
Can confirm this issue. Can reproduce it on my end.
