### ISSUE TITLE
5.2.5 breaks server side rendering of @preact/signals

### ISSUE THREAD

**Issue by Wolfi** [preactjs/preact-render-to-string#272]
Hey guys

https://github.com/preactjs/preact-render-to-string/commit/ad35c4c931db37837761038d33ae71fa31ebc9e3 seems to have broken server side rendering of signals. Demo here https://github.com/Wolfi/preact-render-to-string-signals-issue/blob/main/src/routes/home/index.jsx. 

`foo` and `bar` will only render on the client. With preact-render-to-string pinned to 5.2.4 ssr works as expected.

**Comment by andrewiggins** [comment]
Dupe of preactjs/signals#256. I believe the fix is in preactjs/signals#268 and will be available in the next release of the signals package. Follow preactjs/signals#244 for when that happens.

**Comment by JoviDeCroock** [comment]
This has been released
