### ISSUE TITLE
Meta charset not rendered as expected

### ISSUE THREAD

**Issue by aminnairi** [preactjs/preact-render-to-string#275]
**Describe the bug**
When rendering a meta for encoding the page from the server using `render`, it fails to display the correct attribute casing which should be lowercased for the `S` letter instead it is uppercased just like it is written in JSX.

**To Reproduce**
Follow instructions for the reproduction repository [here](https://github.com/aminnairi/preact-charset-issue-template).

**Expected behavior**
It should render the attribute `charSet` as `charset` when passing through the `render` function for the `<meta>` tag.

**Screenshots**
None.

**Browser (please complete the following information):**
 - OS: [e.g. Windows 11]: Arch
 - Browser [e.g. Chrome 108]: Chrome 108

**Node (please complete the following information):**
 - Platform: [e.g. Node 18]: Node 19.3.0
 - Package Manager [e.g. NPM 8.2.13]: NPM 8.19.2
 - Package Version [e.g. 0.2.1]: 5.2.6

**Additional context**
None.

**Comment by JoviDeCroock** [comment]
Other frameworks don't do this either, it's `charset` and not `char-set` which the camelCased variant would imply, I quickly checked how [react goes about this](https://codesandbox.io/s/adoring-morning-6vpgfb?file=/src/App.js) and they handle it the same way, they don't touch it.
