### ISSUE TITLE
Using effects from @preact/signals causes memory leak

### ISSUE THREAD

**Issue by valentin-huebner** [preactjs/preact-render-to-string#281]
When an effect from @preact/signals is used, a reference to the element that needs to be updated whenever the signal changes is stored inside the signal. An unmount options hook is registered on the element to remove the reference when the element unloads. But with `renderToString()`, the options hook is never run, causing the reference to persist.

**Comment by JoviDeCroock** [comment]
What version are you using, [options.unmount is def called](https://github.com/preactjs/preact-render-to-string/blob/master/src/index.js#L232)

**Comment by valentin-huebner** [comment]
Ah yes, I'm on 5.2.1 for some reason … sorry!
