### ISSUE TITLE
unpkg package seems failed

### ISSUE THREAD

**Issue by studentIvan** [preactjs/preact-render-to-string#291]
```
import { render } from 'https://unpkg.com/preact-render-to-string?module';
```

Uncaught SyntaxError: The requested module 'https://unpkg.com/preact-render-to-string?module' does not provide an export named 'render' (at (index):29:16)

was working yesterday...

**Comment by studentIvan** [comment]
fixed with replace to 
```
import { render } from 'https://esm.sh/preact-render-to-string?module';
```

seems they've changed the origin

**Comment by marvinhagemeister** [comment]
Those are two completly separate projects. It's true though that `esm.sh` is much more modern and way more reliable when it comes to supporting ESM. It can be basically thought of as the successor to `unpkg`.
