### ISSUE TITLE
preact and htm  function does not return html when ssr rendered from mjs file

### ISSUE THREAD

**Issue by VelinGeorgiev** [preactjs/preact-render-to-string#312]
Wondering what am I doing wrong. The code below does not seem to render the component from the server.

- server-http.mjs
```
import http from 'http';
import { h } from 'preact';
import { html } from 'htm/preact';
import render from 'preact-render-to-string';

const host = 'localhost';
const port = 3049;

const App = props => {
  return html`<div>Hello World!</div>`;
}

const server = http.createServer((req, res) => {
  const html = render(App);
  res.writeHead(200);
  res.end(`<!DOCTYPE html><html><body>${html}</body></html>`);
  return;
});

server.listen(port, host, () => {
  console.log(`Server is running on http://${host}:${port}`);
});
```
![Screenshot 2023-08-10 at 19 33 58](https://github.com/preactjs/preact-render-to-string/assets/1049476/72cfe503-0548-46b2-8304-14745c8593de)

When I change the function 

```
const App = props => {
  return html`<div>Hello World!</div>`;
}
```
to template string  
```
const App = html`<div>Hello World!</div>`;
```
it works. 

Just wondering if I am doing something wrong or if this is by design.

Setup:
       Nodejs: 20x
        "preact": "10.16.0",
        "htm": "3.1.1",
        "preact-render-to-string": "6.2.0",

**Comment by VelinGeorgiev** [comment]
OK. I sorted it for myself.  :)

```
import http from 'http';
import { h } from 'preact';
import { html } from 'htm/preact';
import render from 'preact-render-to-string';

const host = 'localhost';
const port = 3049;

const App = ({name}) => {
  return html`<div>Hello ${name}!</div>`;
}

const server = http.createServer((req, res) => {

  const app = render(html`<${App} name="World" />`);

  res.writeHead(200);
  res.end(`<!DOCTYPE html><html><body>${app}</body></html>`);
  return;
});

server.listen(port, host, () => {
  console.log(`Server is running on http://${host}:${port}`);
});
```

**Comment by marvinhagemeister** [comment]
Yup, components need to be called as components. They must pass through the JSX factory function (called behind the scenes in htm) so that Preact creates a component instance.

FYI: Edited your comments to add syntax highlighting. You can add this yourself by adding the file extension to the opening of a fenced code block: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting

**Comment by VelinGeorgiev** [comment]
Thanks @marvinhagemeister!
