### ISSUE TITLE
Incorrect jsx type definition

### ISSUE THREAD

**Issue by acelaya** [preactjs/preact-render-to-string#328]
We have just started to use `preact-render-to-string/jsx` and noticed TypeScript complains because [`jsx.d.ts`](https://github.com/preactjs/preact-render-to-string/blob/cb32a6a4e0b3278ec343a66b1bf8f860309741cd/jsx.d.ts) includes two default exports.

As a temporary workaround we have created our own definition and referenced it via tsconfig's [`paths`](https://www.typescriptlang.org/tsconfig#paths) option.

We could provide a fix for this if desired, consisting in removing the last `export default render;`, which looks like an overlook.

**Comment by marvinhagemeister** [comment]
Good catch, feel free to send a PR. The last default export is definitely a mistake and shouldn't be there.

**Comment by acelaya** [comment]
Thanks! Here's the PR https://github.com/preactjs/preact-render-to-string/pull/329
