### ISSUE TITLE
Stream ESM exports are not being exposed within `/dist` folder

### ISSUE THREAD

**Issue by adwher** [preactjs/preact-render-to-string#366]
Hey there 👋 I was messing around with the new **Stream API** but notice I wasn't able to imported when using a ESM compatible runtime (like Deno) and it's because you're not exposing the `mjs` version within the `/dist` folder but declare it in the `package.json`.

I also check #363 will change the structure of the bundle folder, that will solve this too?

## `package.json`

<img width="448" alt="image" src="https://github.com/preactjs/preact-render-to-string/assets/16128058/19eae04a-92f8-4eb1-a04f-b5b9e1a19a6a">

## `/dist` folder

<img width="815" alt="image" src="https://github.com/preactjs/preact-render-to-string/assets/16128058/f6afac6f-4c3a-4d42-a0ce-f42a5a30648c">

**Comment by rschristian** [comment]
Sorry about that, but already corrected in #362.

Will be in next release.

**Comment by rschristian** [comment]
Released and available in 6.5.3
