### ISSUE TITLE
Context and useState for inter-component state such as CSS for <head>

### ISSUE THREAD

**Issue by pauleveritt** [preactjs/preact-render-to-string#375]
This is likely a basic misunderstanding, though I've read a lot of tickets and tried a lot of code.

I'm working on Preact as an 11ty template language.  I'd like a way for subcomponents to add CSS to `<head>`, as well as some other uses of state during SSR.

`preact-render-to-string` has some support for context and hooks. I tried this:

```tsx
import { createContext } from "preact";
import { useContext, useState } from "preact/hooks";

export const MyContext = createContext();

export function Child() {
  const { value, setValue } = useContext(MyContext);
  // Changing the state has no effect, neither here
  // in child nor in parent.
  setValue(33);
  return (
    <div>
      <p>Value in child: {value}</p>
    </div>
  );
}

export function App() {
  const [value, setValue] = useState(99);
  return (
    <MyContext.Provider value={{ value, setValue }}>
      <div>
        <Child />
        <p>Value in parent: {value}</p>
      </div>
    </MyContext.Provider>
  );
}
```

In a Vitest test:

```tsx
it("should render", async () => {
  const app = <App/>;
  await renderToStringAsync(<App />);
  const result = await renderToStringAsync(app);
  expect(result).toContain("count is 33");
});
```

It still renders with the original `99`. Do I need to trigger some lifecycle method? Render first with Preact, then render to a string? (I saw an experiment from @developit using `undom`.)

**Comment by rschristian** [comment]
This is fundamentally how RTS works, so all's correct there.

`renderToStringAsync` does nothing in your example over `renderToString` -- the async version is meant for thrown promises (Suspense) as it waits to resolve them.

You should never have an unguarded `setState` call within a component like that, so your intentions are a bit unclear, but you could always fall back to `window`/`globalThis` during SSR to pass values around.

**Comment by pauleveritt** [comment]
That's a very interesting point about relying on the outer system for collecting state. Would still need a way to update the node after the tree is rendered.

I think we can close this ticket, as you've confirmed this is behaving as expected.

**Comment by rschristian** [comment]
> Would still need a way to update the node after the tree is rendered.

Do you? If you're just looking to add CSS to the head of the document, and take a semi-standard approach to RTS, something like this could work for you:

```js
const result = renderToString(<App />);

const template = `
<!DOCTYPE html>
<html lang="en">
    <head>
        <style>${globalThis.cssContent}</style>
    </head>
    <body>
        ${result}
        <script type="module" src="/index.jsx"></script>
    </body>
</html>
`;
```

If you do need app state to differ considerably during SSR, a better approach is usually to pass that context in, instead of having components update some state value. For example:

```jsx
export function App({ data }) {
  const [value, setValue] = useState(data || 99);
  return (
    <MyContext.Provider value={{ value, setValue }}>
      <div>
        <Child />
        <p>Value in parent: {value}</p>
      </div>
    </MyContext.Provider>
  );
}

renderToString(<App data={33} />);
```

Takes dependency injection a step further, but lets you better differentiate client from server state initialization a bit better.

**Comment by pauleveritt** [comment]
Thanks @rschristian for the detailed answer. Yes, I was trying to do `useState` from the child component. I've since learned that 11ty's "bundle" support writes a placeholder string in first render, then updates that placeholder after the render with any collected values. I will try something like that.
