### ISSUE TITLE
dangerouslySetInnerHTML={undefined} throws

### ISSUE THREAD

**Issue by birtles** [preactjs/preact-render-to-string#380]
The [type of `dangerouslySetInnerHTML`](https://github.com/preactjs/preact/blob/f5738915a0d67c87f54f0ccd5b946e7a4ce0d5c1/src/index.d.ts#L66-L68) is:

```js
dangerouslySetInnerHTML?: {
  __html: string;
};
```

However, when setting `dangerouslySetInnerHTML` to `undefined` I hit this code here:

https://github.com/preactjs/preact-render-to-string/blob/c8e54a19deb37d8060b01377172ec65bf285b4bf/src/index.js#L122-L135

Here `element` is `undefined` and I get `Cannot read properties of undefined (reading 'then')`.

Using `typeof element?.then === 'function'` seems to fix it for me.

**Comment by marvinhagemeister** [comment]
I'm not able to reproduce the described error on my end. Are you on the latest version? Can you share a snippet that reproduces that triggers the error for you?

**Comment by birtles** [comment]
Oh, sorry about that. I was hitting this via Astro's Preact package and it seemed to come from this changeset: https://github.com/withastro/astro/pull/11464

I'll see if I can work out what is going on when I get a chance.

**Comment by rschristian** [comment]
Thanks, I can reproduce & got a PR created.

I think Marvin was assuming `renderToString`, rather than `renderToStringAsync`, as there wasn't any mention of method (well, other than the code block showing async's internals)
