### ISSUE TITLE
allow custom void elements

### ISSUE THREAD

**Issue by DanielRuf** [preactjs/preact-render-to-string#52]
We have the case that we want to render more elements which can be also void (XML syntax).

It would be good to allow this with an option.
Reference: https://github.com/developit/preact/issues/919

**Comment by developit** [comment]
What would be a way to allow this?

Maybe allow passing `options.void` ?

**Comment by DanielRuf** [comment]
> Maybe allow passing options.void

Would be semantically perfect and a good option.

**Comment by sventschui** [comment]
@DanielRuf is this still a requirement? If so I might be able to implement this or otherwise we might want to close this issue?
