### ISSUE TITLE
Support `componentDidCatch(error)`

### ISSUE THREAD

**Issue by johnhaitas** [preactjs/preact-render-to-string#64]
https://github.com/developit/preact/pull/819 adds support for `componentDidCatch(error)` (note that it currently does not include the `info` argument)

we will need to support `componentDidCatch(error)` to achieve parity with `preact` once that PR is merged in

Note that the `preact` PR https://github.com/developit/preact/pull/819 does not include support for `static getDerivedStateFromError(error)` 
Documentation here: https://reactjs.org/docs/react-component.html#static-getderivedstatefromerror

**Comment by marvinhagemeister** [comment]
Closing, support was added in #305
