### ISSUE TITLE
Support `static getDerivedStateFromError(error)`

### ISSUE THREAD

**Issue by johnhaitas** [preactjs/preact-render-to-string#65]
In addition to supporting `componentDidCatch` (see https://github.com/developit/preact-render-to-string/issues/64) `preact-render-to-string` should support `static getDerivedStateFromError(error)`

Documentation here: https://reactjs.org/docs/react-component.html#static-getderivedstatefromerror

**Comment by marvinhagemeister** [comment]
Closing, support was added in https://github.com/preactjs/preact-render-to-string/pull/305
