### ISSUE TITLE
[5.0.3] Provider with multiple children makes renderToString return <undefined/>

### ISSUE THREAD

**Issue by johannesodland** [preactjs/preact-render-to-string#95]
If a provider has multiple children then the result of a render is an array of VNodes. RenderToString tries to fetch the nodeName of this array on [line 180](https://github.com/preactjs/preact-render-to-string/blob/5.0.3/src/index.js#L180): ```s = `<${nodeName}${s}>`;``` . The result is the string `<undefined>`. 

This breaks server side rendering of valid Preact applications.

```javascript

const TestContext = createContext();
function TestComponent() {
   
   return <TestContext.Provider>
      <div>1</div>
      <div>2</div>
   </TestContext.Provider>
}
```

Preact 10.0.0-beta.2 handles this case by [coercing the array to a fragment](https://github.com/preactjs/preact/blob/10.0.0-beta.2/src/create-element.js#L91):
```javascript
	if (Array.isArray(possibleVNode)) {
		return createElement(Fragment, null, possibleVNode);
	}
```

Maybe preact-render-to-string should coerce the render result to vnodes too?

**Comment by andrewiggins** [comment]
Hi @johannesodland ! Thanks for filing an issue :smile: Looks like #96 fixes this one. Let us know if you find any other bugs.
